// Auto-generated by: supabase gen types typescript --project-id mvwezbknjazxkuwmihrj
// Run `npm run db:types` from root to regenerate after schema changes
// This file is a shell — fill by running the command above after migrations are applied

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          username?: string | null
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          updated_at?: string
        }
      }
      activities: {
        Row: {
          id: string
          creator_id: string
          title: string
          description: string | null
          category_id: string | null
          location_id: string | null
          start_time: string
          end_time: string | null
          max_participants: number
          is_public: boolean
          status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          creator_id: string
          title: string
          description?: string | null
          category_id?: string | null
          location_id?: string | null
          start_time: string
          end_time?: string | null
          max_participants?: number
          is_public?: boolean
          status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled'
        }
        Update: {
          title?: string
          description?: string | null
          category_id?: string | null
          location_id?: string | null
          start_time?: string
          end_time?: string | null
          max_participants?: number
          is_public?: boolean
          status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled'
        }
      }
      activity_messages: {
        Row: {
          id: string
          conversation_id: string
          sender_id: string
          message_type: 'text' | 'image' | 'system'
          content: string | null
          media_url: string | null
          reply_to_id: string | null
          created_at: string
          is_deleted: boolean
        }
        Insert: {
          id?: string
          conversation_id: string
          sender_id: string
          message_type?: 'text' | 'image' | 'system'
          content?: string | null
          media_url?: string | null
          reply_to_id?: string | null
        }
        Update: {
          content?: string | null
          is_deleted?: boolean
        }
      }
      activity_participants: {
        Row: {
          id: string
          activity_id: string
          user_id: string
          role: 'host' | 'co-host' | 'participant'
          joined_at: string
          status: 'active' | 'left' | 'removed'
        }
        Insert: {
          id?: string
          activity_id: string
          user_id: string
          role?: 'host' | 'co-host' | 'participant'
          status?: 'active' | 'left' | 'removed'
        }
        Update: {
          role?: 'host' | 'co-host' | 'participant'
          status?: 'active' | 'left' | 'removed'
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          body: string | null
          type: string
          data: Json
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          body?: string | null
          type: string
          data?: Json
          is_read?: boolean
        }
        Update: {
          is_read?: boolean
        }
      }
      reports: {
        Row: {
          id: string
          reporter_id: string
          target_type: 'user' | 'activity'
          target_id: string
          reason: string
          description: string | null
          status: 'pending' | 'reviewed' | 'dismissed' | 'actioned'
          created_at: string
          reviewed_at: string | null
        }
        Insert: {
          id?: string
          reporter_id: string
          target_type: 'user' | 'activity'
          target_id: string
          reason: string
          description?: string | null
        }
        Update: {
          status?: 'pending' | 'reviewed' | 'dismissed' | 'actioned'
          reviewed_at?: string | null
        }
      }
      feature_flags: {
        Row: {
          id: string
          flag_key: string
          description: string | null
          is_enabled: boolean
          rules: Json
          updated_at: string
        }
        Insert: {
          id?: string
          flag_key: string
          description?: string | null
          is_enabled?: boolean
          rules?: Json
        }
        Update: {
          is_enabled?: boolean
          rules?: Json
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      nearby_activities: {
        Args: {
          lat: number
          lng: number
          radius_km?: number
          category_id?: string | null
          limit_count?: number
          offset_count?: number
        }
        Returns: Array<{
          id: string
          title: string
          description: string | null
          status: string
          start_time: string
          end_time: string | null
          max_participants: number
          creator_id: string
          category_id: string | null
          location_id: string | null
          distance_km: number
          participant_count: number
        }>
      }
    }
    Enums: Record<string, never>
  }
}

